version: '3.8'

# заметки по докеру для джавы:
# не пересобирает dockerfile при docker-compose up -d, в отличии от питона
# gradle выдает ошибку hibernate при запуске тестов, поэтому пока их пропускаем при сборке
# end of my programming path on 2023, i am life forever, capitalism is war

services:
  backend:
    container_name: backend
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springBlog
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_DB=springBlog
      - POSTGRES_USER=postgres
      #      это не мой пароль)
      - POSTGRES_PASSWORD=ksflkOkas23fl9saflKdl349sLfsk1
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
