version: '3.8'
services:
  backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springBlog
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_DB=springBlog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ksflkOkas23fl9saflKdl349sLfsk1
    #    ports:
    #      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped



volumes:
  db-data:
